In [1]:
from pathlib import Path

import pandas as pd

from langchain_community.document_loaders import (
    PyPDFDirectoryLoader
)

print("Imports loaded")

/var/folders/j8/89knmx2x01x_sd7sjjggjvlw0000gn/T/ipykernel_58352/955405037.py:5: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import (

Imports loaded

In [2]:
DATA_DIR = "./data"

print(
    "Dataset Folder:",
    DATA_DIR
)

Dataset Folder: ./data

In [6]:
# data validation
pdfs = list(Path(DATA_DIR).glob( "*.pdf"))

print("PDF Count:",len(pdfs))
print("\nPDF Files:")

for i, f in enumerate(pdfs):
    print(f"{i+1}. {f.name}")

PDF Count: 26

PDF Files:
1. FORM -10I.pdf
2. FORM 10IA.pdf
3. FAQs on New Tax Regime.pdf
4. Validate_Digital_Signature.pdf
5. PPT on submitting transfer forms online.pdf
6. DECLARATION FOR NOT HOLDING ANY OTHER HOUSE PROPERTY.pdf
7. Leave_Encashment_Declaration.pdf
8. Form 12B - IT.pdf
9. Form 12C - IT.pdf
10. User Guide for Employee profile.pdf
11. notes_to_investment_proof_submission.pdf
12. EPSF_Reasons_for_Rejection.pdf
13. Instructions for Filling Form 13 IN.pdf
14. Dependent Checklist.pdf
15. Instructions for Filling Form 19.pdf
16. Instructions for Filling Form 2.pdf
17. Form 13 - PF.pdf
18. Form 10C - PF.pdf
19. form_12_BB.pdf
20. Jan Feb March Rent Declaration Format.pdf
21. gratuity_declaration.pdf
22. User Guide for Investment Proof (Stohrm Scan copy submission).pdf
23. Form 19 - PF.pdf
24. Instructions for Filling Form 13 IN (1).pdf
25. Instructions for Filling Form 10C.pdf
26. Rent_Receipt.pdf

                ┌──────────────────────┐
                │   PDF / Documents     │
                │---------------------- │
                │ Instructions          │
                │ Legal Docs            │
                │ Tax Forms             │
                │ Screenshots           │
                │ User Manuals          │
                └─────────┬────────────┘
                          │
                          ▼
         ┌─────────────────────────────┐
         │ Document Ingestion Layer     │
         │-----------------------------│
         │ Upload / API / Batch         │
         │ Metadata Extraction          │
         │ Version Tracking             │
         └─────────┬───────────────────┘
                   │
                   ▼
     ┌──────────────────────────────────┐
     │ Document Understanding Layer      │
     │---------------------------------- │
     │ OCR (if scanned)                  │
     │ Layout Parsing                    │
     │ Table Extraction                  │
     │ Image Captioning                  │
     │ Structure Detection               │
     └──────────┬───────────────────────┘
                │
                ▼
     ┌──────────────────────────────────┐
     │ Intelligent Chunking Layer        │
     │---------------------------------- │
     │ Semantic Chunking                 │
     │ Parent Child Chunk                │
     │ Table Chunking                    │
     │ Metadata Tagging                  │
     └──────────┬───────────────────────┘
                │
                ▼
     ┌─────────────────────────────────┐
     │ Embedding Pipeline               │
     │--------------------------------- │
     │ Text Embeddings                  │
     │ Hybrid Sparse Dense              │
     │ Metadata Embedding               │
     └──────────┬──────────────────────┘
                │
                ▼
      ┌───────────────────────────────┐
      │ Storage Layer                  │
      │------------------------------- │
      │ Vector DB                      │
      │ Metadata Store                 │
      │ Object Storage                 │
      └──────────┬────────────────────┘
                 │
                 ▼
        ┌─────────────────────────┐
        │ Retrieval Engine         │
        │-------------------------│
        │ Query Expansion          │
        │ Hybrid Search            │
        │ Re-ranking               │
        │ Context Compression      │
        └────────┬────────────────┘
                 │
                 ▼
     ┌────────────────────────────┐
     │ LLM Generation Layer        │
     │----------------------------│
     │ Prompt Builder              │
     │ Grounding                   │
     │ Citation                    │
     └──────────┬─────────────────┘
                │
                ▼
          User Response

### Data Ingetion

In [7]:
# models and imports
from pathlib import Path
import pandas as pd
from langchain_community.document_loaders import PyPDFDirectoryLoader
from langchain_ollama import ChatOllama, OllamaEmbeddings

llm = ChatOllama(model="qwen:latest", temperature=0)
embedding_model = OllamaEmbeddings(model="nomic-embed-text:latest")

print("Ready")

Ready

In [8]:
# config dataset and retriever
DATA_DIR = "./data"
pdf_files = sorted(Path(DATA_DIR).glob("*.pdf"))

print(f"PDFs Found: {len(pdf_files)}")
[f.name for f in pdf_files]

PDFs Found: 26

['DECLARATION FOR NOT HOLDING ANY OTHER HOUSE PROPERTY.pdf',
 'Dependent Checklist.pdf',
 'EPSF_Reasons_for_Rejection.pdf',
 'FAQs on New Tax Regime.pdf',
 'FORM -10I.pdf',
 'FORM 10IA.pdf',
 'Form 10C - PF.pdf',
 'Form 12B - IT.pdf',
 'Form 12C - IT.pdf',
 'Form 13 - PF.pdf',
 'Form 19 - PF.pdf',
 'Instructions for Filling Form 10C.pdf',
 'Instructions for Filling Form 13 IN (1).pdf',
 'Instructions for Filling Form 13 IN.pdf',
 'Instructions for Filling Form 19.pdf',
 'Instructions for Filling Form 2.pdf',
 'Jan Feb March Rent Declaration Format.pdf',
 'Leave_Encashment_Declaration.pdf',
 'PPT on submitting transfer forms online.pdf',
 'Rent_Receipt.pdf',
 'User Guide for Employee profile.pdf',
 'User Guide for Investment Proof (Stohrm Scan copy submission).pdf',
 'Validate_Digital_Signature.pdf',
 'form_12_BB.pdf',
 'gratuity_declaration.pdf',
 'notes_to_investment_proof_submission.pdf']

In [9]:
## load pdf
loader = PyPDFDirectoryLoader(DATA_DIR)
documents = loader.load()

print(f"Pages Loaded: {len(documents)}")

Unexpected escaped string: u
Unexpected escaped string: i
Unexpected escaped string: F
Unexpected escaped string: F

Pages Loaded: 161

In [10]:
# insoect data
doc = documents[0]

print(doc.metadata)
print(doc.page_content[:1000])

{'producer': 'Acrobat Distiller 4.05 for Windows', 'creator': 'Microsoft Word 9.0', 'creationdate': 'D:20050615143620', 'uri': 'G:\\Taxmann_Projects\\ITRules_2004\\FormsFolder\\DataRules\\forms\\', 'moddate': '2005-06-15T14:36:23+05:30', 'author': 'administrator', 'source': 'data/FORM -10I.pdf', 'total_pages': 1, 'page': 0, 'page_label': '1'}
Printed from www.taxmann.com
FORM NO. 10-I
[See rule 11DD]
Certificate of prescribed authority for the purposes of section 80DDB


1.  Name of the Patient

2.  Address

3.  Father’s name

4.  Name and address of the person on whom the patient is dependent
and his relationship with the patient.


5.  Name of the disease or ailment
(please see rule 11DD)


6.  For diseases or ailments mentioned in item (i) of clause (a) of
sub-rule (1), whether the disability is 40% or more (Please specify
the extent).


7.  Name, address, registration number and qualification of the
specialist issuing the certificate, along with the name and address
of the Government hospital [see rule 11DD(2)]



Verification
This is to verify that I, Dr.____________________________________________________ s/o (w/o)
Shri_____________________, in the case of the patient Shri/Smt./Ms.________________________, after
considering the entire history of illness, careful examination and

In [13]:
# creating metadata table
metadata_df = pd.DataFrame([
{
"source": Path(d.metadata["source"]).name,
"page": d.metadata.get("page",0),
"chars": len(d.page_content),
"words": len(d.page_content.split()),
"text": d.page_content
}
for d in documents
])

metadata_df.head()

,source,page,chars,words,text
0,FORM -10I.pdf,0,1747,238,Printed from www.taxmann.com \nFORM NO. 10-I \...
1,FORM 10IA.pdf,0,1262,125,[IPrinted From Taxmann’s Income Tax Rules on C...
2,FAQs on New Tax Regime.pdf,0,2239,402,Q1. Why should I opt for new Tax regime? \nAns...
3,FAQs on New Tax Regime.pdf,1,2227,405,"Ans. Once old tax regime is opted, you cannot ..."
4,FAQs on New Tax Regime.pdf,2,2715,475,"Ans. As per the Income Tax amendment 2023, def..."

In [15]:
metadata_df.shape

(161, 5)

In [16]:
metadata_df.describe()

             page        chars        words
count  161.000000   161.000000   161.000000
mean    15.813665  1118.124224   176.627329
std     18.992171  1099.411949   263.749237
min      0.000000     0.000000     0.000000
25%      1.000000   402.000000    57.000000
50%      7.000000   705.000000   101.000000
75%     25.000000  1316.000000   175.000000
max     65.000000  4769.000000  2084.000000

In [17]:
# classify the doucments
def classify(x):
    x=x.lower()
    if "guide" in x: return "guide"
    if "form" in x or "declaration" in x: return "form"
    if "tax" in x: return "tax"
    if "policy" in x: return "policy"
    if "faq" in x: return "faq"
    return "other"

metadata_df["doc_type"] = metadata_df["source"].apply(classify)

metadata_df[["source","doc_type"]].head()

                       source doc_type
0               FORM -10I.pdf     form
1               FORM 10IA.pdf     form
2  FAQs on New Tax Regime.pdf      tax
3  FAQs on New Tax Regime.pdf      tax
4  FAQs on New Tax Regime.pdf      tax